Allow null values on SlugRelatedField
ico-apps/django-importer pull request #58
Opened 2024-02-23 11:52 UTC by EloiR

If a SlugRelatedField didn't find an object on the database, it raised ObjectDoesNotExist error and import failed. 
However, model field might be nullable. 

This PR tries to fix this situation. If ObjectDoesNotExist arises but model field has attribute null=True, it will return None instead of a ValidationError.

2024-02-23 12:31 UTC, utoPiC commented on djimporter/fields.py
> +
Maybe you can do it before the try.  Not need to try to find the object value if value ==''. It can raise  if value not found but not ''

2024-02-26 13:13 UTC, slamora requested changes
I think that the code is not solving the issue. How has it been tested?

P.D.: I've added a unit test that is failing when tries to import a row with empty value on a nullable field.

2024-02-27 12:11 UTC, slamora commented
@EloiR I've refactored the code. It's a bit hacky because validation is based on django built-in model validation.

`field.null` means that could be `NULL` at database level.
`field.blank` means that could be empty at form level (and also for importer).

This is why we need to by-pass this default behaviour. The other options is to refactor importer to don't relay on built-in model validation.

2024-02-27 13:30 UTC, slamora approved these changes

2024-02-27 13:30 UTC, merged